### ISSUE TITLE
the flickering is a bit too Obvious

### ISSUE THREAD

**Issue by jasoncow007** [ShmuelRonen/ComfyUI-CohernetVideoSampler#1]
Is there any way to reduce the flicker?https://github.com/user-attachments/assets/cb877c85-b858-4856-ad98-d1ed853c3dd4

**Comment by ShmuelRonen** [comment]
Working on it. Stay tuned for updates.
You can also use Frame Interpolation node to smooth the movement.

**Comment by ShmuelRonen** [comment]
There is a new version
